package:
  name: pango
  version: "1.36.5"

source:
  fn: pango-1.36.5.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/1.36/pango-1.36.5.tar.xz
  sha256: be0e94b2e5c7459f0b6db21efab6253556c8f443837200b8736d697071276ac8

build:
  number: 0

about:
  home: http://www.pango.org
  license: GNU Lesser General Public License (LGPL) version 2.1 or the Mozilla Public License (MPL) version 1.1 at your option.
